% Generated by ADiMat 0.6.6-5530 (00419e1f)
% © 2001-2008 Andre Vehreschild <vehreschild@sc.rwth-aachen.de>
% © 2009-2018 Johannes Willkomm <johannes@johannes-willkomm.de>
% TU Darmstadt, 64289 Darmstadt, Germany
% Visit us on the web at http://www.adimat.de/
% Report bugs to johannes@johannes-willkomm.de
%
%                             DISCLAIMER
% 
% ADiMat was prepared as part of an employment at the Institute for Scientific Computing,
% RWTH Aachen University, Germany and at the Institute for Scientific Computing,
% TU Darmstadt, Germany and is provided AS IS. 
% NEITHER THE AUTHOR(S), THE GOVERNMENT OF THE FEDERAL REPUBLIC OF GERMANY
% NOR ANY AGENCY THEREOF, NOR THE RWTH AACHEN UNIVERSITY, NOT THE TU DARMSTADT,
% INCLUDING ANY OF THEIR EMPLOYEES OR OFFICERS, MAKES ANY WARRANTY, EXPRESS OR IMPLIED,
% OR ASSUMES ANY LEGAL LIABILITY OR RESPONSIBILITY FOR THE ACCURACY, COMPLETENESS,
% OR USEFULNESS OF ANY INFORMATION OR PROCESS DISCLOSED, OR REPRESENTS THAT ITS USE
% WOULD NOT INFRINGE PRIVATELY OWNED RIGHTS.
%
% Parameters:
%  - dependents=out
%  - independents=x
%  - inputEncoding=ISO-8859-1
%
% Functions in this file: a_myfunction, rec_myfunction,
%  ret_myfunction
%

function [a_x nr_out] = a_myfunction(x, a_out)
   tmpca2 = 2 .* x;
   tmpca1 = x .^ 2;
   out = tmpca1 + tmpca2;
   nr_out = out;
   [a_tmpca1 a_tmpca2 a_x] = a_zeros(tmpca1, tmpca2, x);
   if nargin < 2
      a_out = a_zeros1(out);
   end
   a_tmpca1 = adimat_adjsum(a_tmpca1, adimat_adjred(tmpca1, a_out));
   a_tmpca2 = adimat_adjsum(a_tmpca2, adimat_adjred(tmpca2, a_out));
   a_x = adimat_adjsum(a_x, adimat_adjred(x, 2 .* x.^1 .* a_tmpca1));
   a_x = adimat_adjsum(a_x, adimat_adjred(x, 2 .* a_tmpca2));
end

function out = rec_myfunction(x)
   tmpca2 = 2 .* x;
   tmpca1 = x .^ 2;
   out = tmpca1 + tmpca2;
   adimat_push(tmpca1, tmpca2, out, x);
end

function a_x = ret_myfunction(a_out)
   [x out tmpca2 tmpca1] = adimat_pop;
   [a_tmpca1 a_tmpca2 a_x] = a_zeros(tmpca1, tmpca2, x);
   if nargin < 1
      a_out = a_zeros1(out);
   end
   a_tmpca1 = adimat_adjsum(a_tmpca1, adimat_adjred(tmpca1, a_out));
   a_tmpca2 = adimat_adjsum(a_tmpca2, adimat_adjred(tmpca2, a_out));
   a_x = adimat_adjsum(a_x, adimat_adjred(x, 2 .* x.^1 .* a_tmpca1));
   a_x = adimat_adjsum(a_x, adimat_adjred(x, 2 .* a_tmpca2));
end
