% Generated by ADiMat 0.6.6-5530 (00419e1f)
% © 2001-2008 Andre Vehreschild <vehreschild@sc.rwth-aachen.de>
% © 2009-2018 Johannes Willkomm <johannes@johannes-willkomm.de>
% TU Darmstadt, 64289 Darmstadt, Germany
% Visit us on the web at http://www.adimat.de/
% Report bugs to johannes@johannes-willkomm.de
%
%                             DISCLAIMER
% 
% ADiMat was prepared as part of an employment at the Institute for Scientific Computing,
% RWTH Aachen University, Germany and at the Institute for Scientific Computing,
% TU Darmstadt, Germany and is provided AS IS. 
% NEITHER THE AUTHOR(S), THE GOVERNMENT OF THE FEDERAL REPUBLIC OF GERMANY
% NOR ANY AGENCY THEREOF, NOR THE RWTH AACHEN UNIVERSITY, NOT THE TU DARMSTADT,
% INCLUDING ANY OF THEIR EMPLOYEES OR OFFICERS, MAKES ANY WARRANTY, EXPRESS OR IMPLIED,
% OR ASSUMES ANY LEGAL LIABILITY OR RESPONSIBILITY FOR THE ACCURACY, COMPLETENESS,
% OR USEFULNESS OF ANY INFORMATION OR PROCESS DISCLOSED, OR REPRESENTS THAT ITS USE
% WOULD NOT INFRINGE PRIVATELY OWNED RIGHTS.
%
% Parameters:
%  - dependents=frev
%  - independents=x
%  - inputEncoding=ISO-8859-1
%
% Functions in this file: a_myfunction_rm, rec_myfunction_rm,
%  ret_myfunction_rm
%

function [a_x nr_frev] = a_myfunction_rm(x, a_frev)
   tmpca2 = 2 .* x;
   tmpca1 = x .^ 2;
   frev = tmpca1 + tmpca2;
   nr_frev = frev;
   [a_tmpca1 a_tmpca2 a_x] = a_zeros(tmpca1, tmpca2, x);
   if nargin < 2
      a_frev = a_zeros1(frev);
   end
   a_tmpca1 = adimat_adjsum(a_tmpca1, adimat_adjred(tmpca1, a_frev));
   a_tmpca2 = adimat_adjsum(a_tmpca2, adimat_adjred(tmpca2, a_frev));
   a_x = adimat_adjsum(a_x, adimat_adjred(x, 2 .* x.^1 .* a_tmpca1));
   a_x = adimat_adjsum(a_x, adimat_adjred(x, 2 .* a_tmpca2));
end

function frev = rec_myfunction_rm(x)
   tmpca2 = 2 .* x;
   tmpca1 = x .^ 2;
   frev = tmpca1 + tmpca2;
   adimat_push(tmpca1, tmpca2, frev, x);
end

function a_x = ret_myfunction_rm(a_frev)
   [x frev tmpca2 tmpca1] = adimat_pop;
   [a_tmpca1 a_tmpca2 a_x] = a_zeros(tmpca1, tmpca2, x);
   if nargin < 1
      a_frev = a_zeros1(frev);
   end
   a_tmpca1 = adimat_adjsum(a_tmpca1, adimat_adjred(tmpca1, a_frev));
   a_tmpca2 = adimat_adjsum(a_tmpca2, adimat_adjred(tmpca2, a_frev));
   a_x = adimat_adjsum(a_x, adimat_adjred(x, 2 .* x.^1 .* a_tmpca1));
   a_x = adimat_adjsum(a_x, adimat_adjred(x, 2 .* a_tmpca2));
end
